substitutions:
  devicename: esp32epaper

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
  platformio_options: 
    upload_speed: 921600
    board_build.f_flash: 80000000L

packages:
  wifi: !include wifi.yaml
  mqtt: !include mqtt.yaml
#  ble: !include ble.yaml

# Enable logging
logger:
  level: DEBUG
#  level: ERROR


time:
  - platform: sntp
    servers : 192.168.11.1

web_server:
  port: 80

switch:
  - platform: restart
    name: "$devicename Restart"

text_sensor:
  - platform: mqtt_subscribe
    name: "AussenTemperatur"
    id: sensorAussenTemperatur
    topic: AussenTemperatur
  - platform: mqtt_subscribe
    name: "AussenLuftfeuchte"
    id: sensorAussenLuftfeuchte
    topic: AussenLuftfeuchte

uart:
  rx_pin: GPIO26
  tx_pin: GPIO25
  baud_rate: 9600

sensor:
  - platform: uptime
    name: "$devicename Uptime Sensor"

  - platform: wifi_signal
    name: "$devicename WiFi Signal Sensor"
    update_interval: 60s

  - platform: mhz19
    co2:
      name: "$devicename MH-Z19 CO2 Value"
      id: sensorMHZ19CO2
    temperature:
      name: "$devicename MH-Z19 Temperature"
      id: sensorMHZ19Temperatur
    update_interval: 60s
    automatic_baseline_calibration: false

spi:
  clk_pin: GPIO19
  mosi_pin: GPIO18
#  miso_pin: GPIO5

font:
  - file: "Roboto-Regular.ttf"
    id: fontRoboto
    size: 20

display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO14
    busy_pin: GPIO21
    reset_pin: GPIO22
    model: 7.50inV2
    update_interval: 60s
    id: my_display
    lambda: |-
      it.print(0, 100, id(fontRoboto), "Hello World! und nu fuer mehr...");
      it.printf(0, 200, id(fontRoboto), "Aussentemperatur ist: %s", id(sensorAussenTemperatur).state.c_str());
      it.printf(0, 220, id(fontRoboto), "AussenLuftfeuchte ist: %s", id(sensorAussenLuftfeuchte).state.c_str());
      it.printf(0, 260, id(fontRoboto), "MH-Z19 CO2 Value: %.0f", id(sensorMHZ19CO2).state);
      it.printf(0, 280, id(fontRoboto), "MH-Z19 Temperature: %.1f", id(sensorMHZ19Temperatur).state);


# Example configuration entry
deep_sleep:
  run_duration: 10s
  sleep_duration: 1min
  id: deep_sleep_1

