substitutions:
  devicename: esp32epaper
  
globals:
  - id: prevent_sleep
    type: bool
    restore_value: no
    initial_value: "false"
  - id: valueCount
    type: int
    restore_value: no
    initial_value: "0"
    
esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
  platformio_options: 
    upload_speed: 921600
    board_build.f_flash: 80000000L
  on_boot:
    priority: -100
    then:
      - logger.log: "boot ready..."
      # - delay: 1s
      # - logger.log: "delayed 1s... update display"
      # - component.update: my_display      
      # - delay: 6s
      # - logger.log: "delayed 6s..."
      - if:
          condition:
            lambda: 'return id(prevent_sleep);'
          then:
            - logger.log: "OTA Mode"
          else:
            if:
              condition:
                # adjust sleep time to hour of the day
                lambda: 'return ((id(current_time).now().hour < 6) || (id(current_time).now().hour > 22)) ;'
              then:
                - logger.log: "nighttime..."
                - lambda: 'id(deep_sleep_1).set_sleep_duration(5*60*1000);'
                # - deep_sleep.enter: deep_sleep_1
              else:
                - logger.log: "daytime..."
                - lambda: 'id(deep_sleep_1).set_sleep_duration(60*1000);'
                # - deep_sleep.enter: deep_sleep_1      
  on_loop:
    then:
      - if:
          condition:
            lambda: 'return (id(valueCount) == 7) ;'
          then:
            - logger.log: "all values ready..."
            - lambda: 'id(valueCount) += 1;'
            - component.update: my_display
            # - lambda: 'WiFi.mode(WIFI_OFF);'
            - delay: 8s
            - logger.log: "delayed 8s..."
            - deep_sleep.enter: deep_sleep_1
          # else:
            # - logger.log: "waiting for values..."
packages:
  wifi: !include wifi.yaml
#  ble: !include ble.yaml


mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: false
  client_id: $devicename
  on_message: # Manueller refresh des Displays bei Änderung
    - topic: $devicename/input/refresh_display
      payload: "1"
      then:
        - component.update: my_display
    - topic: $devicename/input/ota_mode
      payload: '1'
      then:
        - globals.set:
            id: prevent_sleep
            value: 'true'
        - deep_sleep.prevent: deep_sleep_1
    - topic: $devicename/input/sleep_mode
      payload: '1'
      then:
        - deep_sleep.enter: deep_sleep_1

# Enable logging
logger:
  # level: DEBUG
  level: ERROR


time:
 - platform: sntp
   id: current_time
   timezone: Europe/Vienna
   servers : 192.168.11.1

#web_server:
#  port: 80

#switch:
#  - platform: restart
#    name: "$devicename Restart"

text_sensor:
  - platform: mqtt_subscribe
    id: moonPhase
    topic: esp32epaper/input/MoonPhase
    on_value:
      then:
        - lambda: 'id(valueCount) += 1;'
 
uart:
  rx_pin: GPIO26
  tx_pin: GPIO25
  baud_rate: 9600

sensor:
#  - platform: uptime
#    name: "$devicename Uptime Sensor"

  - platform: mqtt_subscribe
    id: outside_temperature
    topic: esp32epaper/input/AussenTemperatur
    on_value:
      then:
        - lambda: 'id(valueCount) += 1;'

  - platform: mqtt_subscribe
    id: sensorAussenLuftfeuchte
    topic: esp32epaper/input/AussenLuftfeuchte
    on_value:
      then:
        - lambda: 'id(valueCount) += 1;'

  - platform: mqtt_subscribe
    id: inside_temperature
    topic: esp32epaper/input/InsideTemperature
    on_value:
      then:
        - logger.log: "Value recieved..."
        - lambda: 'id(valueCount) += 1;'

  - platform: mqtt_subscribe
    id: InsideHumidity
    topic: esp32epaper/input/InsideHumidity
    on_value:
      then:
        - logger.log: "Value recieved..."
        - lambda: 'id(valueCount) += 1;'

  - platform: mqtt_subscribe
    id: top_consumer
    topic: esp32epaper/input/PVPower
    on_value:
      then:
        - logger.log: "Value recieved..."
        - lambda: 'id(valueCount) += 1;'

  - platform: mqtt_subscribe
    topic: esp32epaper/input/TotalPower
    id: sparsnas
    on_value:
      then:
        - logger.log: "Value recieved..."
        - lambda: 'id(valueCount) += 1;'

  - platform: wifi_signal
    name: "$devicename WiFi Signal Sensor"
    id: wifisignal
    update_interval: 5min


spi:
  clk_pin: GPIO19
  mosi_pin: GPIO18
#  miso_pin: GPIO5

font:
  - file: "fonts/Roboto-Regular.ttf"
    id: fontRoboto
    size: 40
  - file: 'fonts/Google_Sans_Bold.ttf'
    id: clock_font
    size: 90
    glyphs: [0, 1, 2, 3, 4, 5, 6, 7 ,8, 9, ':']
  - file: 'fonts/Google_Sans_Medium.ttf'
    id: temp_font
    size: 55
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z','å', 'ä', 'ö', '/']
  - file: 'fonts/Google_Sans_Bold.ttf'
    id: status_font
    size: 36
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', 'å', 'ä', 'ö', '/']
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 70
    glyphs: [
      '', # mdi-account-heart
      '', # mdi-thermometer
      "", # mdi-water-percent
      '󰅢', # mdi-fire-hydrant
      "", # mdi-umbrella
      "ｲ", # mdi-home-thermometer-outline
      "ｱ", # mdi-home-thermometer
      "", # sun rise
      "", # sun set
      "\U000F029A", # Pressure
      "\U000F15FA", # Wind
      "\U000F058C", # Rain
      "\U000F0E02", # Tempmin
      "\U000F0E03", # Tempmax
      "\U000F0150", # Clock
      
      "", # wind
      
      # Moon
      "ﾁ", # new_moon
      "ﾄ", # waxing_crecent
      "ｾ", # first_quarter
      "ﾅ", # waxing_gibbous
      "ｿ", # full_moon
      "ﾃ", # waning_gibbous
      "ﾀ", # last_quarter
      "ﾂ", # waning_crescent
      # Sun
      "", # mdi-weather-sunset-down
      "", # mdi-weather-sunset-up
      ]
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: weather_font
    size: 50
    glyphs: [
      '', # mdi-account-heart
      '', # mdi-thermometer
      '󰅢', # mdi-fire-hydrant
      "", # mdi-umbrella
      "ｲ", # mdi-home-thermometer-outline F0F55
      
      # Wifi
      '冷', # mdi-wifi-strength-outline
      '爛', # mdi-wifi-strength-1
      '嵐', # mdi-wifi-strength-2
      '襤', # mdi-wifi-strength-3
      '蠟', # mdi-wifi-strength-4

      ]

display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO14
    busy_pin: GPIO21
    reset_pin: GPIO22
    model: 7.50inV2
    update_interval: never
    id: my_display
    lambda: |
      int x, y;
      ESP_LOGI("display", "Updating..");

      /* Print time in HH:MM format */
      it.strftime(125, -10, id(clock_font), TextAlign::TOP_CENTER, "%H:%M", id(current_time).now());

      //it.line(259, -10, 259, 200);it.line(261, 0, 261, 200);it.line(260, 0, 260, 200);
      //it.line(0, 200, 259, 200);it.line(0, 201, 261, 201);it.line(0, 202, 260, 202);
      /*
      it.print(125, 120, id(temp_font), TextAlign::BASELINE_CENTER, "HELLO SUNSHINE!");
      it.print(125, 160, id(icon_font), TextAlign::BASELINE_CENTER, "");
      it.print(125, 182, id(temp_font), TextAlign::BASELINE_CENTER, "Lea & Emma"); // 400 - ((400 - 260)/2)
      */
      /* Moon icon */
      if(id(moonPhase).has_state()) {
        y = 355, x = 230;
        ESP_LOGI("Moon icon", "%s", id(moonPhase).state.c_str());
        it.printf(x, y, id(icon_font), TextAlign::BASELINE_CENTER, "%s", id(moonPhase).state.c_str());
      }
      /* WiFi Signal Strenght */
      if(id(wifisignal).has_state()) {
        x = 798, y = 478;
        if (id(wifisignal).state >= -50) {
            //Excellent
            it.print(x, y, id(weather_font), TextAlign::BOTTOM_RIGHT, "蠟");
            ESP_LOGI("WiFi", "Exellent");
        } else if (id(wifisignal).state  >= -60) {
            //Good
            it.print(x, y, id(weather_font), TextAlign::BOTTOM_RIGHT, "襤");
            ESP_LOGI("WiFi", "Good");
        } else if (id(wifisignal).state  >= -67) {
            //Fair
            it.print(x, y, id(weather_font), TextAlign::BOTTOM_RIGHT, "嵐");
            ESP_LOGI("WiFi", "Fair");
        } else if (id(wifisignal).state  >= -70) {
            //Weak
            it.print(x, y, id(weather_font), TextAlign::BOTTOM_RIGHT, "爛");
            ESP_LOGI("WiFi", "Weak");
        } else {
            //Unlikely working signal
            it.print(x, y, id(weather_font), TextAlign::BOTTOM_RIGHT, "冷");
            ESP_LOGI("WiFi", "Unlikely");
        }
      }


      // Print inside temperature (from homeassistant sensor)
      y = 155, x = 102;
      if (id(inside_temperature).has_state()) {
        it.print(x, y, id(icon_font), TextAlign::BOTTOM_RIGHT, "ｱ");
        it.printf(x+2, y, id(temp_font), TextAlign::BOTTOM_LEFT , "%6.1f°C", id(inside_temperature).state);
        }
      if (id(InsideHumidity).has_state()) {
        it.printf(x+x+x+x, y, id(icon_font), TextAlign::BOTTOM_LEFT, ""); 
        it.printf(x+x+x+x+x/2, y, id(temp_font), TextAlign::BOTTOM_LEFT , "%3.0f%%", id(InsideHumidity).state);
        }
      // Print outside temperature (from homeassistant sensor)
      if (id(outside_temperature).has_state()) {
        it.print(x, y, id(icon_font), TextAlign::TOP_RIGHT, "ｲ"); 
        it.printf(x+2, y, id(temp_font), TextAlign::TOP_LEFT, "%6.1f°C", id(outside_temperature).state);
      }
      if (id(sensorAussenLuftfeuchte).has_state()) {
        it.printf(x+x+x+x, y, id(icon_font), TextAlign::TOP_LEFT, ""); 
        it.printf(x+x+x+x+x/2, y, id(temp_font), TextAlign::TOP_LEFT, "%3.0f%%", id(sensorAussenLuftfeuchte).state);
      }
      // Print consumer
      if (id(top_consumer).has_state()) {
        it.printf(0, 480, id(temp_font), TextAlign::BOTTOM_LEFT , "Verbr.: %.0f W, PV: %.0f W", id(sparsnas).state, id(top_consumer).state);
      }
      // it.line(0, 299, 400, 299);



# Example configuration entry
deep_sleep:
  run_duration: 15s
  sleep_duration: 2min
  id: deep_sleep_1

